# Site settings
title: KruXXX
email: your-email@domain.com
description: cruquiusweg 120A 1019AK Amsterdam
twitter_username: jekyllrb
github_username:  jekyll

url: 
baseurl:	/kruxamsterdam.eu 

# Build settings
markdown: kramdown
include: ['_pages']