title:            Krux
description:      Krux is the best
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              
disqus_shortname:
baseurl: 		/krux-website/

# Owner/author information
owner:
  name:           Krux artist collective
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:
  facebook:
  github:
  stackoverflow:
  linkedin:
  instagram:
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

#UTF-8
encoding: UTF-8

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Amsterdam
future:      true
highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/