# Site settings
title: KruXXX
email: your-email@domain.com
description: > 
  Dit is de website voor Cruquius artist collective
twitter_username: jekyllrb
github_username:  jekyll

baseurl: /krux-website/

# Build settings
markdown: kramdown
include: ['_pages']