# Site settings
title: KruXXX
email: your-email@domain.com
description: News
twitter_username: jekyllrb
github_username:  jekyll

url: 
baseurl:	/krux-website 

# Build settings
markdown: kramdown
include: ['_pages']