# Site settings
title: KruXXX
email: your-email@domain.com
description: > 
  01-05-2015: krux open studios!
twitter_username: jekyllrb
github_username:  jekyll

url: 
baseurl:	/krux-website 

# Build settings
markdown: kramdown
include: ['_pages']